# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga_archivos', '0001_initial'),
        ('procesamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procesamiento',
            old_name='procesamiento_dir',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='procesamiento',
            name='carga',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='carga_archivos.Carga'),
            preserve_default=False,
        ),
    ]
