# -*- coding: utf-8 -*-
"""
Sistema de modelado de Tópicos v1.4

Copyleft (@) 2017 CENDITEL nodo Mérida - https://planificacion.cenditel.gob.ve/trac/wiki/ModeladoTopicos_2017
"""
## @package carga_archivos.models
#
# Modelos de la aplicación de carga de archivos
# @author Generated by 'django-admin startproject' using Django 1.11.
# @author Rodrigo Boet (rboet at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
# @version 1.4
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

class Carga(models.Model):
    """!
    Clase que gestiona el guardado de la carga de archivos

    @author Rodrigo Boet (rboet at cenditel.gob.ve)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 30-08-2017
    @version 1.0.0
    """
    
    ## Campo con el nombre del directorio
    carga_dir = models.CharField(max_length=30)
    
    ## Relación con el user
    user = models.ForeignKey(User)
    
    ## Listado de los directorios
    directorios = 0
    
