# -*- coding: utf-8 -*-
"""
Sistema de modelado de Tópicos v1.4

Copyleft (@) 2017 CENDITEL nodo Mérida - https://planificacion.cenditel.gob.ve/trac/wiki/ModeladoTopicos_2017
"""
## @package users.urls
#
# Urls base de la aplicación de Usuario
# @author Generated by 'django-admin startproject' using Django 1.11.
# @author Rodrigo Boet (rboet at cenditel.gob.ve)
# @author <a href='http://www.cenditel.gob.ve'>Centro Nacional de Desarrollo e Investigación en Tecnologías Libres
# (CENDITEL) nodo Mérida - Venezuela</a>
# @copyright <a href='https://www.gnu.org/licenses/gpl-3.0.en.html'>GNU Public License versión 3 (GPLv3)</a>
# @version 1.4
from django.conf.urls import url
from django.contrib.auth.views import *
from .forms import PasswordResetForm, PasswordConfirmForm
from .views import Register, Login
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'inicio'}, name='logout'),
    url(r'^register/$', Register.as_view(), name='register'),    
    #url(r'^update/(?P<pk>\d+)$', PerfilUpdate.as_view(), name = "update"),
    url(r'^password/reset/$', password_reset,
        {'post_reset_redirect': '/password/done/',
         'template_name': 'user.reset.html', 'password_reset_form':PasswordResetForm}, name="reset"),
    url(r'^password/done/$', password_reset_done,
        {'template_name': 'user.passwordreset.done.html'},
        name='reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {'template_name': 'user.passwordreset.confirm.html', 'set_password_form':PasswordConfirmForm,
         'post_reset_redirect': '/password/end/'},
        name='password_reset_confirm'),
    url(r'^password/end/$', password_reset_done,
        {'template_name': 'user.passwordreset.end.html'},
        name='reset_end'),
]